### ISSUE TITLE
Melisma highlighting on Verovio rendered chant + UX update for Melisma number

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#43]

**Comment by notkaramel** [comment]
@martha-thomae This issue was raised by Ich during our last meeting (a week ago I think) and I implemented it. It's looking like this 
![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/d4157a79-5395-417b-b19b-9cc852bad0c1)

Do you think it looks good?

**Comment by martha-thomae** [comment]
Hmmm, I would prefer for it to highlight the notes themselves (rather than having individual bounding boxes around each note). Did you do it this way so that it doesn't conflict with the melodic search? If this is the case, would it be possible to highlight the syllable (the text underneath the melisma) instead?

**Comment by notkaramel** [comment]
Hmm you got a great point. I haven't tried highlighting the syllable text before, will try that!

**Comment by notkaramel** [comment]
- Resolved in #55 
- The final implementation is to highlight the syllable word instead of all the notes as shown below
![image](https://github.com/ECHOES-from-the-Past/mei-analyser/assets/24505220/c752a202-15dd-4d9a-ae63-928c961b2f5b)
