### ISSUE TITLE
Neume grouping

### ISSUE THREAD

**Issue by notkaramel** [ECHOES-from-the-Past/mei-analyser#58]
As suggested during the seminar on Monday, there should be a feature to detect grouping of notes `<nc>` within a `<neume>`.

**Comment by martha-thomae** [comment]
I am not sure what this is. @elsinhadl, do you know about this? It seems this was a point Katarina brought up. Do you remember?

**Comment by notkaramel** [comment]
If I remember correctly, she was interested in groups of notes within a neume. For example

```xml
<syl wordpos="t" xml:id="m-a898a3d6-2fec-11ef-a1ac-3645f29ecd15">te</syl>
  <neume xml:id="m-a898a3f4-2fec-11ef-a1ac-3645f29ecd15">
    <nc xml:id="m-a898a41c-2fec-11ef-a1ac-3645f29ecd15" pname="g" oct="2"/>
    <nc xml:id="m-a898a43a-2fec-11ef-a1ac-3645f29ecd15" pname="a" oct="2"/>
    <nc xml:id="m-a898a458-2fec-11ef-a1ac-3645f29ecd15" pname="b" oct="2"/>
    <nc xml:id="m-a898a480-2fec-11ef-a1ac-3645f29ecd15" pname="c" oct="3"/>
    <nc xml:id="m-a898a49e-2fec-11ef-a1ac-3645f29ecd15" pname="b" oct="2"/>
  </neume>
  <neume xml:id="m-a898a4c6-2fec-11ef-a1ac-3645f29ecd15">
    <nc tilt="n" xml:id="m-a898a4ee-2fec-11ef-a1ac-3645f29ecd15" pname="b" oct="2"/>
    <nc xml:id="m-a898a50c-2fec-11ef-a1ac-3645f29ecd15" pname="a" oct="2"/>
  </neume>
</syl>
```

The first group of notes (5 notes) is within the first `<neume/>`, and the second group of notes (2 notes) is within the second `<neume/>`

**Comment by elsinhadl** [comment]
To be honest, I don't recall that she was interested in group of notes within a single neume. Perhaps she wanted to search for a specific series of notes (or contour) within a single syllable?

**Comment by martha-thomae** [comment]
Hmmm, maybe she refer to be able to see the individual neumes in a syllable. In other words, to be able to distinguish the boundaries between one neume and the next in a syllable. That is a Verovio issue. And, thankfully, it is solved now, so we can close this one! :) 

See this from the latest main version:
<img width="1470" alt="Screenshot 2024-07-08 at 13 30 28" src="https://github.com/ECHOES-from-the-Past/mei-analyser/assets/13948831/9f637b42-a6c4-4bc9-baf4-4cb6ff50b4d0">


Against this from the latest commit in develop:
<img width="1470" alt="Screenshot 2024-07-08 at 13 30 23" src="https://github.com/ECHOES-from-the-Past/mei-analyser/assets/13948831/6a6f4651-14c9-4e8b-b86f-88e8418f25f2">

Even the oblique ligatures are fixed in this last version (with the downward stroke placed next to the oblique ligature).

**Comment by notkaramel** [comment]
Oh that's wonderful! I hope they will update the npm package soon
