### ISSUE TITLE
Display information for Aquitanian mode detection

### ISSUE THREAD

**Issue by martha-thomae** [ECHOES-from-the-Past/mei-analyser#60]
Add a section for `Mode Description` that includes the following items for Aquitanian script:
* Finalis position
* Rhombuses position
* Repercussios position

Please, if you have enough time, rephrase the integer values (e.g., `-2`) into number of steps below/above the line (e.g., two steps below the line).

**Comment by martha-thomae** [comment]
> * Repercussios position

Here are some options for phrasing this:

- The repeated notes are located at -2 (7 times), +1 (4 times), ...

- The notes ordered according to their number appearances are: -2 (7 times), +1 (4 times), ...
 
- Ordered notes according to their appearance: -2 (7 times), ...
 
- Repercussio in descending order of appearance are at -2 (7 times), +1 (4 times), ...

And include a clarification that these positions are steps above/below relative to the reference line.

**Comment by notkaramel** [comment]
From the [wiki mode page](https://github.com/ECHOES-from-the-Past/mei-analyser/wiki/Mode-Detection-for-Aquitanian-Script) and probably quoted from the ECHOES report 2023:
> ## 8th mode
> The last note (G) is placed on the line.
> The rhomboidal punctum can be found exclusively **two step above the line (B)** or **two steps below the line (B)**

@martha-thomae @elsinhadl can you check if the pitch above/below the line is correct here? Since the line is G, two steps above would be `B` (correct) and two steps below would be `E` (incorrect).

**Comment by elsinhadl** [comment]
Correct!
